# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.CharField(max_length=50)),
                ('plate', models.CharField(max_length=20)),
                ('description', models.TextField(default='', null=True)),
                ('category', models.CharField(choices=[('Standard', 'Standard'), ('Cruiser', 'Cruiser'), ('Sport bike', 'Sport bike'), ('Touring', 'Touring'), ('Sport touring', 'Sport touring'), ('Dual-sport', 'Dual-sport'), ('Scooters', 'Scooters'), ('Off-road', 'Off-road'), ('Enclosed', 'Enclosed'), ('Utility', 'Utility'), ('Tricycles', 'Tricycles')], default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.CharField(max_length=50)),
                ('plate', models.CharField(max_length=20)),
                ('description', models.TextField(default='', null=True)),
                ('category', models.CharField(choices=[('SUV', 'SUV'), ('Truck', 'Truck'), ('Sedan', 'Sedan'), ('Van', 'Van'), ('Coupe/Compact', 'Coupe/Compact'), ('Wagon', 'Wagon'), ('Convertible', 'Convertible'), ('Sports Car', 'Sports Car'), ('Diesel', 'Diesel'), ('Crossover', 'Crossover'), ('Luxury Car', 'Luxury Car'), ('Hybrid/Electric', 'Hybrid/Electric'), ('Hatchback', 'Hatchback'), ('Certified Pre-Owned', 'Certified Pre-Owned')], default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('description', models.TextField(default='', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.Rental'),
        ),
        migrations.AddField(
            model_name='bike',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.Rental'),
        ),
    ]
