# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='model',
            field=models.CharField(default='suzuki', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default='suzuki', max_length=200),
            preserve_default=False,
        ),
    ]
