# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_auto_20161108_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='slug',
            field=models.SlugField(default='aaa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(default='aaa', max_length=100),
            preserve_default=False,
        ),
    ]
