# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-28 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_auto_20161108_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Truck', 'Truck'), ('Sedan', 'Sedan'), ('Van', 'Van'), ('Coupe/Compact', 'Coupe/Compact'), ('Wagon', 'Wagon'), ('Convertible', 'Convertible'), ('Sports Car', 'Sports Car'), ('Diesel', 'Diesel'), ('Crossover', 'Crossover'), ('Luxury Car', 'Luxury Car'), ('Hybrid/Electric', 'Hybrid/Electric'), ('Hatchback', 'Hatchback')], default='', max_length=200),
        ),
    ]
