# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-02 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_auto_20170125_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='car_image')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rentals.Car')),
            ],
        ),
        migrations.AddField(
            model_name='rental',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
