# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-28 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
