# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-23 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20170105_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenities'},
        ),
    ]
