# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-25 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_auto_20170123_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=8),
            preserve_default=False,
        ),
    ]
