# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-26 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_auto_20170126_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelimage',
            old_name='image',
            new_name='images',
        ),
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, upload_to='hotel_image'),
        ),
    ]
