# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-26 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_auto_20170126_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelimage',
            old_name='images',
            new_name='image',
        ),
    ]
