# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-01 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_auto_20170130_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
