# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-23 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20170123_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingitem',
            old_name='booking_id',
            new_name='booking',
        ),
    ]
