# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-25 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_auto_20170123_1400'),
        ('booking', '0006_auto_20170123_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRoom',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('hotels.room',),
        ),
    ]
