# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-31 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sight',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sight',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
