# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-19 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='home_address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_numer',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
